name: Accessibility Audit (axe + Playwright)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  a11y:
    name: Accessibility Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Get Vercel preview URL
        id: vercel
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const vercelComment = comments.data.find(c =>
              c.user?.login === 'vercel[bot]' && c.body?.includes('Visit Preview')
            );

            if (vercelComment) {
              const match = vercelComment.body.match(/\[Visit Preview\]\((.*?)\)/);
              if (match) {
                core.setOutput('preview-url', match[1]);
              }
            }

      - name: Run Playwright a11y tests
        id: run-a11y
        env:
          PREVIEW_URL: ${{ steps.vercel.outputs.preview-url }}
        run: |
          echo "::group::Running a11y tests"
          echo "URL: $PREVIEW_URL"
          mkdir -p results/a11y
          npx playwright test --project=chromium || true
          echo "::endgroup::"

      - name: Upload accessibility report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a11y-report
          path: results/a11y/**

      - name: Comment (or update) PR with accessibility report
        if: github.event.pull_request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            const runId = process.env.GITHUB_RUN_ID;
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const vercelUrl = process.env.PREVIEW_URL || '${{ steps.vercel.outputs.preview-url }}';
            const reportPath = 'results/a11y/accessibility-report.md';

            let summary = '';
            try {
              summary = fs.readFileSync(reportPath, 'utf8');
            } catch (e) {
              summary = '⚠️ *Erreur lors de la lecture du rapport Markdown généré.*';
            }

            const body = [
              '<!-- a11y-report -->', // 🏷️ ancre unique
              '## ♿ Rapport d’accessibilité automatique (Playwright + axe-core)',
              '',
              `🔗 **URL testée** : [${vercelUrl}](${vercelUrl})`,
              '',
              `📄 **Rapport complet** : [Artefacts GitHub Actions](https://github.com/${owner}/${repo}/actions/runs/${runId})`,
              '',
              '---',
              '',
              '### ✅ Résumé :',
              '',
              summary,
              '',
              '---',
              '',
              '🛠 *Ce rapport a été généré automatiquement par CI via axe-core. Merci de corriger les éléments ci-dessus pour améliorer l’accessibilité.*'
            ].join('\n');

            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number,
              per_page: 100
            });

            const existing = comments.find(c =>
              c.user?.type === 'Bot' &&
              c.body?.includes('<!-- a11y-report -->')
            );

            if (existing) {
              await github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: existing.id,
                body
              });
              core.info(`Commentaire a11y mis à jour (#${existing.id})`);
            } else {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body
              });
              core.info('Nouveau commentaire a11y créé');
            }

      - name: Résumé dans GitHub Actions
        if: always()
        run: |
          echo "## ✅ Résumé Playwright A11y & Core" >> $GITHUB_STEP_SUMMARY
          if test -f results/a11y/accessibility-report.md; then
            echo "### Rapport axe-core" >> $GITHUB_STEP_SUMMARY
            cat results/a11y/accessibility-report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Rapport axe-core non généré" >> $GITHUB_STEP_SUMMARY
          fi
