name: Lighthouse CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  lighthouse:
    name: Audit Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run Lighthouse CI
        run: npx lhci autorun

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lhci-report/

      - name: Get Vercel preview URL
        id: vercel
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const vercelComment = comments.data.find(c =>
              c.user?.login === 'vercel[bot]' && c.body?.includes('Visit Preview')
            );

            if (vercelComment) {
              const match = vercelComment.body.match(/\[Visit Preview\]\((.*?)\)/);
              if (match) {
                core.setOutput('preview-url', match[1]);
              }
            }

      - name: Comment (or update) PR with Lighthouse summary
        if: github.event.pull_request
        uses: actions/github-script@v7
        env:
          PREVIEW_URL: ${{ steps.vercel.outputs.preview-url }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const previewBase   = process.env.PREVIEW_URL ?? '';
            const runUrl        = `https://github.com/${owner}/${repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;

            const manifestPath = './lhci-report/manifest.json';
            const summary      = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

            const toEmoji = score => {
              const pct = Math.round(score * 100);
              if (pct >= 90) return '🟢';
              if (pct >= 50) return '🟠';
              return '🔴';
            };
            const pct = v => Math.round(v * 100);

            const rows = summary
              .map(({ url, summary: s, htmlPath }) => {
                const pathname  = new URL(url).pathname;
                const liveUrl   = previewBase ? `${previewBase}${pathname}` : url;
                return `| [\`${pathname}\`](${liveUrl}) | ${toEmoji(s.performance)} ${pct(s.performance)} | ${toEmoji(s.accessibility)} ${pct(s.accessibility)} | ${toEmoji(s['best-practices'])} ${pct(s['best-practices'])} | ${toEmoji(s.seo)} ${pct(s.seo)} |`;
              })
              .join('\n');

            const body = [
              '<!-- lhci-report -->',                     // <-- marque unique
              '## 📊 Lighthouse report',
              '',
              `*Workflow run: [link](${runUrl})*`,
              '',
              '| Page | Performance | Accessibility | Best Practices | SEO |',
              '|------|-------------|----------------|----------------|-----|',
              rows
            ].join('\n');

            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number,
              per_page: 100
            });

            const existing = comments.find(c =>
              c.user?.type === 'Bot' &&               
              c.body?.includes('<!-- lhci-report -->')
            );

            if (existing) {
              await github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: existing.id,
                body
              });
              core.info(`Comment mis à jour : #${existing.id}`);
            } else {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body
              });
              core.info('Nouveau commentaire créé');
            }
